/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fnnas-softlink-docker': RouteRecordInfo<
      '/posts/fnnas-softlink-docker',
      '/posts/fnnas-softlink-docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Introduction-to-Oceanography-Notes': RouteRecordInfo<
      '/posts/Introduction-to-Oceanography-Notes',
      '/posts/Introduction-to-Oceanography-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MusicFree': RouteRecordInfo<
      '/posts/MusicFree',
      '/posts/MusicFree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Probability-Statistics-Notes': RouteRecordInfo<
      '/posts/Probability-Statistics-Notes',
      '/posts/Probability-Statistics-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Russian1-Grammar': RouteRecordInfo<
      '/posts/Russian1-Grammar',
      '/posts/Russian1-Grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Russian1-Note': RouteRecordInfo<
      '/posts/Russian1-Note',
      '/posts/Russian1-Note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser_91fa91d014e2cc218aedf4bf27adf5fc/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/fnnas-softlink-docker.md': {
      routes:
        | '/posts/fnnas-softlink-docker'
      views:
        | never
    }
    'pages/posts/Introduction-to-Oceanography-Notes.md': {
      routes:
        | '/posts/Introduction-to-Oceanography-Notes'
      views:
        | never
    }
    'pages/posts/MusicFree.md': {
      routes:
        | '/posts/MusicFree'
      views:
        | never
    }
    'pages/posts/Probability-Statistics-Notes.md': {
      routes:
        | '/posts/Probability-Statistics-Notes'
      views:
        | never
    }
    'pages/posts/Russian1-Grammar.md': {
      routes:
        | '/posts/Russian1-Grammar'
      views:
        | never
    }
    'pages/posts/Russian1-Note.md': {
      routes:
        | '/posts/Russian1-Note'
      views:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
