/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Fnnas-Softlink-Docker': RouteRecordInfo<
      '/posts/Fnnas-Softlink-Docker',
      '/posts/Fnnas-Softlink-Docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Introduction-to-Oceanography-Notes': RouteRecordInfo<
      '/posts/Introduction-to-Oceanography-Notes',
      '/posts/Introduction-to-Oceanography-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Look-Tongji-Notes': RouteRecordInfo<
      '/posts/Look-Tongji-Notes',
      '/posts/Look-Tongji-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Marine-Engineering-Environment-Note': RouteRecordInfo<
      '/posts/Marine-Engineering-Environment-Note',
      '/posts/Marine-Engineering-Environment-Note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MusicFree': RouteRecordInfo<
      '/posts/MusicFree',
      '/posts/MusicFree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Petrology-Example': RouteRecordInfo<
      '/posts/Petrology-Example',
      '/posts/Petrology-Example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Petrology-Organize': RouteRecordInfo<
      '/posts/Petrology-Organize',
      '/posts/Petrology-Organize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Petrology-Problem': RouteRecordInfo<
      '/posts/Petrology-Problem',
      '/posts/Petrology-Problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Probability-Statistics-Notes': RouteRecordInfo<
      '/posts/Probability-Statistics-Notes',
      '/posts/Probability-Statistics-Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Russian1-Grammar': RouteRecordInfo<
      '/posts/Russian1-Grammar',
      '/posts/Russian1-Grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Russian1-Note': RouteRecordInfo<
      '/posts/Russian1-Note',
      '/posts/Russian1-Note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_ae14f9cf30ae35891959fe32100f129f/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_e59c8b3e16a357695ff120ae11af6ceb/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_ae14f9cf30ae35891959fe32100f129f/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_ae14f9cf30ae35891959fe32100f129f/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/Fnnas-Softlink-Docker.md': {
      routes:
        | '/posts/Fnnas-Softlink-Docker'
      views:
        | never
    }
    'pages/posts/Introduction-to-Oceanography-Notes.md': {
      routes:
        | '/posts/Introduction-to-Oceanography-Notes'
      views:
        | never
    }
    'pages/posts/Look-Tongji-Notes.md': {
      routes:
        | '/posts/Look-Tongji-Notes'
      views:
        | never
    }
    'pages/posts/Marine-Engineering-Environment-Note.md': {
      routes:
        | '/posts/Marine-Engineering-Environment-Note'
      views:
        | never
    }
    'pages/posts/MusicFree.md': {
      routes:
        | '/posts/MusicFree'
      views:
        | never
    }
    'pages/posts/Petrology-Example.md': {
      routes:
        | '/posts/Petrology-Example'
      views:
        | never
    }
    'pages/posts/Petrology-Organize.md': {
      routes:
        | '/posts/Petrology-Organize'
      views:
        | never
    }
    'pages/posts/Petrology-Problem.md': {
      routes:
        | '/posts/Petrology-Problem'
      views:
        | never
    }
    'pages/posts/Probability-Statistics-Notes.md': {
      routes:
        | '/posts/Probability-Statistics-Notes'
      views:
        | never
    }
    'pages/posts/Russian1-Grammar.md': {
      routes:
        | '/posts/Russian1-Grammar'
      views:
        | never
    }
    'pages/posts/Russian1-Note.md': {
      routes:
        | '/posts/Russian1-Note'
      views:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
